UKBB:
    scenarios:
        SIRgeouniform:
        SIRcenter1geo10000:
        SIRcenter1geo50000:
        SIRcenter1geo100000:
        SIRcenter2geo10000:
        SIRcenter2geo50000:
        SIRcenter2geo100000:
        SIRcenter3geo10000:
        SIRcenter3geo50000:
        SIRcenter3geo100000:
        SIRpcauniform:
        SIRcenter1pca0.0005:
        SIRcenter1pca0.0025:
        SIRcenter1pca0.005:
        SIRcenter2pca0.0005:
        SIRcenter2pca0.0025:
        SIRcenter2pca0.005:
        SIRcenter3pca0.0005:
        SIRcenter3pca0.0025:
        SIRcenter3pca0.005:
        #closest10kpca:
        #closest10kgeo:
        #uniform:
        #1epsilonpca:
        #5epsilonpca:
        #10epsilonpca:
        #50epsilonpca:
        #100epsilonpca:

        #5epsilongeo:
        #10epsilongeo:
        #50epsilongeo:
        #uniformgeo:
        #5epsilonpcaIS:
        #10epsilonpcaIS:
        #50epsilonpcaIS:
        #100epsilonpcaIS:
        #uniformpcaIS:
        #5epsilongeoIS:
        #10epsilongeoIS:
        #50epsilongeoIS:
        #uniformgeoIS:
