UKBB:
    scenarios:
        uniform:
        #1epsilonpca:
        5epsilonpca:
        10epsilonpca:
        50epsilonpca:
        100epsilonpca:
        closest10kpca:
        5epsilongeo:
        10epsilongeo:
        50epsilongeo:
        closest10kgeo:
        uniformgeo:
        5epsilonpcaIS:
        10epsilonpcaIS:
        50epsilonpcaIS:
        100epsilonpcaIS:
        uniformpcaIS:
        5epsilongeoIS:
        10epsilongeoIS:
        50epsilongeoIS:
        uniformgeoIS:
